build_docker_image:
  base_image: ubuntu:16.04

build_image:
  commands:
    $extend:
      - "apt-get update"
      - "apt-get install --yes alien"
      - "apt-get install --yes unzip"
      - "wget --quiet -P /tmp/ https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-linux-x86-64.zip"
      - "unzip /tmp/bcl2fastq2-v2-20-0-linux-x86-64.zip -d /tmp/"
      - "alien -i /tmp/bcl2fastq2-v2.20.0.422-Linux-x86_64.rpm"
      - "curl -L https://cf.10xgenomics.com/releases/cell-exp/cellranger-5.0.1.tar.gz?Expires=1609214486&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZi4xMHhnZW5vbWljcy5jb20vcmVsZWFzZXMvY2VsbC1leHAvY2VsbHJhbmdlci01LjAuMS50YXIuZ3oiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MDkyMTQ0ODZ9fX1dfQ__&Signature=b0Q8XENq08jz2t5MXtIpQ-HRnDPCIqPdadkAOfZjbSNqEwrqbbkRCMevCG9RHc14G1yUgbdoBKprVkkHeUSpRTDJjTkATwbz0-eXsx92SWqPQG59jmvcGFA5r0c~X7hScQzOJ58-G5PuUEvyGjVnxC0bM661JdGnGzZojR4vjr284lEmYjktTgk597R8C~phefyFfSxiLosjNmYK3cnAeLa99qx8vpZe-qYOYq9E9Go8oqLhIPx~6E9IfoQbA87iLm8kt31PY-RT4mgnyOiTM-tGN4mFPNI46q7eMxy5MEAQC5XljZM1lEVDgGH-2o6kWEKMv15lgOZ6UNoFFmezVA__&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA > /tmp/cellranger.tar.gz"
      - "tar xfz /tmp/cellranger.tar.gz -C /tmp"
      - "mv /tmp/cellranger-5.0.1/* /usr/bin/"
      - "wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh"
      - "bash /tmp/miniconda.sh -b -p $HOME/anaconda"
      - "PATH=$HOME/anaconda/bin:$PATH"
      - "conda config --set always_yes yes --set changeps1 no"
      - "conda update -q conda"
      - "conda config --add channels defaults"
      - "conda config --add channels conda-forge"
      - "conda config --add channels bioconda"
      - "conda install -n root _license"
      - "conda info -a"
      - "git clone https://github.com/thsuanwu/utilities.git"
      - "cd utilities"
      - "python setup.py install"
